### ISSUE TITLE
OSCam config files not R/W

### ISSUE THREAD

**Issue by macca-au** [ogra1/oscam-snap#1]
Hi, trying OSCam thru Snap install, config files cannot be edited/deleted, even with root access.   What am I doing wrong - yes I know it's me that is the problem :)

**Comment by ogra1** [comment]
the config files for oscam live in /var/snap/oscam/current/etc/oscam/ and are writable there:
```
ogra@kodi:~$ ls /var/snap/oscam/current/etc/oscam/
oscam.ccache    oscam.dvbapi    oscam.provid      oscam.services  oscam.user.bak
oscam.conf      oscam.emmcache  oscam.server      oscam.srvid     oscam.whitelist
oscam.conf.bak  oscam.emmstat   oscam.server.bak  oscam.user      tpl
ogra@kodi:~$
```
